sudo: true
services:
  - postgresql
addons:
  postgresql: "9.6"
language: python
matrix:
  include:
    - python: 3.6
      env:
      - TOX_ENV=lint
    - python: 3.7
      dist: xenial
      env:
      - TOX_ENV=py37-postgres
    - python: 3.7
      dist: xenial
      env:
      - TOX_ENV=py37-sqlite
      - SQLITE_BUILD=1
    - python: 3.6
      env:
      - TOX_ENV=py36-postgres
    - python: 3.6
      env:
      - TOX_ENV=py36-sqlite
      - SQLITE_BUILD=1
    - python: 3.6
      env:
        # To check old SQLite version
      - TOX_ENV=py36-sqlite
    - python: 3.5
      env:
      - TOX_ENV=py35-postgres
    - python: 3.5
      env:
      - TOX_ENV=py35-sqlite
      - SQLITE_BUILD=1
    - python: 3.4
      env:
      - TOX_ENV=py34-postgres
    - python: 3.4
      env:
      - TOX_ENV=py34-sqlite
      - SQLITE_BUILD=1
    - python: 2.7
      env:
      - TOX_ENV=py27-postgres
    - python: 2.7
      env:
      - TOX_ENV=py27-sqlite
      - SQLITE_BUILD=1
    - python: pypy3
      env:
      - TOX_ENV=pypy3-postgres
    - python: pypy3
      env:
      - TOX_ENV=pypy3-sqlite
      - SQLITE_BUILD=1
    - python: pypy
      env:
      - TOX_ENV=pypy-postgres
    - python: pypy
      env:
      - TOX_ENV=pypy-sqlite
      - SQLITE_BUILD=1
script:
  - tox -e $TOX_ENV
before_install:
  - if [ $SQLITE_BUILD = 1 ]; then sudo add-apt-repository -y ppa:jonathonf/backports && sudo apt-get update && sudo apt-get install --only-upgrade sqlite3; fi
install:
  - travis_retry pip install tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
