sudo: true
services:
  - postgresql
addons:
  postgresql: "9.6"
language: python
matrix:
  include:
    - python: 3.6
      env:
      - TOX_ENV=lint
    - python: 3.6
      env:
      - TOX_ENV=py36-postgres
    - python: 3.6
      env:
      - TOX_ENV=py36-sqlite
    - python: 3.5
      env:
      - TOX_ENV=py35-postgres
    - python: 3.5
      env:
      - TOX_ENV=py35-sqlite
script:
  - tox -e $TOX_ENV
before_install:
  - sudo add-apt-repository -y ppa:jonathonf/backports
  - sudo apt-get update
  - sudo apt-get install --only-upgrade sqlite3
  - sudo sqlite3 -version
install:
  - travis_retry pip install tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
