sudo: true
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    sources:
      - travis-ci/sqlite3
    packages:
      - sqlite3
language: python
matrix:
  include:
    - python: 3.6
      env:
      - TOX_ENV=lint
    - python: 3.6
      env:
      - TOX_ENV=py36
script:
  - tox -e $TOX_ENV
before_install:
  - sudo apt-get autoremove sqlite3
  - sudo apt-get install python-software-properties
  - sudo apt-add-repository -y ppa:travis-ci/sqlite3
  - sudo apt-get -y update
  - sudo apt-cache show sqlite3
  - sudo apt-get install sqlite3=3.7.15.1-1~travis1
  - sudo sqlite3 -version
install:
  - travis_retry pip install tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
