[tool.black]
line-length = 120
target_version = ["py37"]

[tool.isort]
# config compatible with Black
line_length = 120
multi_line_output = 3
default_section = "THIRDPARTY"
include_trailing_comma = true
known_first_party = "xdump"
known_third_party = ["attr", "click", "django", "psycopg2", "pytest", "setuptools", "sphinx_rtd_theme"]
